blank_issues_enabled: false
contact_links:
  - name: Are there any issues you're experiencing with Swiftwave?
    url: https://community.swiftwave.org/
    about: Join us on Discord to meet members, contributors and the maintainer and brainstorm ideas.
