name: Cleanup Untagged Images

on:
  workflow_call:
    secrets:
      SWIFTWAVE_DELETE_PACKAGE:
        description: 'token to delete packages of switwave'
        required: true 
jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: swiftwave-org
          name: swiftwave
          token: ${{ secrets.SWIFTWAVE_DELETE_PACKAGE }}
          untagged-keep-latest: 1
